"""
migrations/versions/0001_initial.py - Initial VCC schema migration.
"""
from __future__ import annotations
import os, sys
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _bcrypt_hash(plain: str) -> str:
    backend_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if backend_root not in sys.path:
        sys.path.insert(0, backend_root)
    from passlib.context import CryptContext
    return CryptContext(schemes=["bcrypt"], deprecated="auto").hash(plain)


def upgrade() -> None:
    bind = op.get_bind()
    # NB: server defaults use sa.func.now(), not sa.text("now()") - the latter is
    # literal PostgreSQL SQL and SQLite has no now() function. func.now() renders
    # now() on PostgreSQL and CURRENT_TIMESTAMP on SQLite.

    # locations
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False, unique=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
    )

    # cameras
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("location_id", sa.Integer(),
                  sa.ForeignKey("locations.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("lane_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("rtsp_url", sa.String(1024), nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="inactive"),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True, server_default=sa.func.now()),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
    )

    # users
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("role", sa.String(32), nullable=False, server_default="viewer"),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # events
    op.create_table(
        "events",
        # BIGINT PRIMARY KEY does not autoincrement on SQLite (only the literal
        # type "INTEGER" aliases rowid); BIGINT is preserved on PostgreSQL.
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer, "sqlite"),
                  primary_key=True, autoincrement=True),
        sa.Column("camera_id", sa.Integer(),
                  sa.ForeignKey("cameras.id", ondelete="CASCADE"), nullable=False),
        sa.Column("location_id", sa.Integer(),
                  sa.ForeignKey("locations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("lane_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_class", sa.String(32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("crossing_dir", sa.String(8), nullable=False, server_default="in"),
        sa.Column("timestamp", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_events_location_timestamp", "events", ["location_id", "timestamp"])
    op.create_index("ix_events_vehicle_class_timestamp", "events", ["vehicle_class", "timestamp"])
    op.create_index("ix_events_camera_timestamp", "events", ["camera_id", "timestamp"])

    # alerts
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("camera_id", sa.Integer(),
                  sa.ForeignKey("cameras.id", ondelete="CASCADE"), nullable=True),
        sa.Column("alert_type", sa.String(32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.Column("acknowledged", sa.Boolean(), nullable=False, server_default="false"),
    )

    # Analytics views. Plain views (not MATERIALIZED) so the same DDL shape works
    # on PostgreSQL and SQLite, and so they are always current - no refresh job.
    # The dialect-specific truncation SQL is generated by backend/db_dialect.py,
    # which is also what creates these at application startup.
    dialect = bind.dialect.name
    if dialect == "sqlite":
        hour_expr = "strftime('%Y-%m-%d %H:00:00.000000', timestamp)"
        day_expr = "date(timestamp)"
    else:
        hour_expr = "date_trunc('hour', timestamp)"
        day_expr = "CAST(date_trunc('day', timestamp) AS date)"

    op.execute(
        "CREATE VIEW mv_hourly_counts AS "
        "SELECT location_id, vehicle_class, {h} AS hour, COUNT(*) AS total_count "
        "FROM events GROUP BY location_id, vehicle_class, {h}".format(h=hour_expr)
    )
    op.execute(
        "CREATE VIEW mv_daily_totals AS "
        "SELECT vehicle_class, {d} AS day, COUNT(*) AS total_count "
        "FROM events GROUP BY vehicle_class, {d}".format(d=day_expr)
    )
    op.execute(
        "CREATE VIEW mv_lane_counts AS "
        "SELECT camera_id, lane_id, vehicle_class, COUNT(*) AS total_count "
        "FROM events GROUP BY camera_id, lane_id, vehicle_class"
    )

    # Seed admin user
    hashed_pw = _bcrypt_hash("Admin1234!")
    if dialect == "sqlite":
        insert_sql = (
            "INSERT OR IGNORE INTO users (email, hashed_password, role) "
            "VALUES (:email, :pw, 'admin')"
        )
    else:
        insert_sql = (
            "INSERT INTO users (email, hashed_password, role) "
            "VALUES (:email, :pw, 'admin') ON CONFLICT (email) DO NOTHING"
        )
    bind.execute(sa.text(insert_sql).bindparams(email="admin@vcc.local", pw=hashed_pw))


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS mv_lane_counts")
    op.execute("DROP VIEW IF EXISTS mv_daily_totals")
    op.execute("DROP VIEW IF EXISTS mv_hourly_counts")
    op.drop_table("alerts")
    op.drop_table("events")
    op.drop_table("users")
    op.drop_table("cameras")
    op.drop_table("locations")
